print("\n---------------------------------------------------------------------------------------------\n  Seja bem vindo! Este exercício apresenta algumas operações arítméticas, desenvolvido como\n   exercício da Disciplina de Computational Thinking do Curso de Analise e Desenvolvimento\n                              de Sistemas da FIAP turma 2021!\n--------------------------------------------------------------------------------------------- ")
a = input("Informe um numero qualquer inteiro: >>> ")
b = input("Informe agora um segundo numero inteiro: >>> ")
print("\nConfira as operações e seus resultados abaixo:\n---------------------------------------------------------------------------------------------")
soma = int(a)+int(b)
multiplica = int(a)*int(b)
divisao = int(a)/int(b)
resto = int(a)%int(b)
print("A soma destes dois números é >>> ", soma," <<<")
print("A multiplicação deles, resulta em >>> ", multiplica," <<<")
print("O quociente inteiro é >>> ", (int(divisao))," <<<")
print("O resto deles, é >>> ", resto," <<<")
