soma = 0
valor = input ("Digite um numero:__")
soma = soma + int(valor)
print ("Seu subtotal é "+ (str(soma)))
print (" ")
valor = input ("Digite outro número:__")
soma = soma + int(valor)
print ("Seu subtotal é "+ (str(soma)))
print (" ")
valor = input ("Digite outro número:__")
soma = soma + int(valor)
print ("Seu subtotal é "+ (str(soma)))
print (" ")
valor = input ("Digite outro número:__")
soma = soma + int(valor)
print ("Seu subtotal é "+ (str(soma)))
print (" ")
valor = input ("Digite outro número:__")
soma = soma + int(valor)
print ("Seu subtotal é "+ (str(soma)))