dado = input('Qual o seu nome? ')
arquivo = open(dado + '.txt', mode='w')
arquivo.write('Nome->' + dado + '\n')
dado = input('Quantos anos você tem? ')
arquivo.write('Idade->' + dado + '\n')
dado = input('Último curso formal que você iniciou (ensino médio, faculdade, etc)? ')
arquivo.write('Curso->' + dado + '\n')
dado = input('Ocupação? ')
arquivo.write('Ocupação->' + dado + '\n')
dado = input('Por que escolheu TI como campo de trabalho? ')
arquivo.write('Escolha->' + dado + '\n')
dado = input('Dentro da área de TI no que gostaria de trabalhar (desenvolvimento, análise, ...)? ')
arquivo.write('Desejo->' + dado + '\n')
dado = input('Quais são seus hobbies e esportes que pratica? ')
arquivo.write('Hobbies->' + dado + '\n')
arquivo.close()
print('Procure o arquivo <seu nome>.txt, verifique se suas respostas estão presentes e envie para o email profeduardo@fiap.com.br\nObrigado!')